services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - "EUREKA_SERVER=http://discovery-server:8761/eureka"
    depends_on:
      - discovery-server

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - "EUREKA_SERVER=http://discovery-server:8761/eureka"
      - "DB_URL=jdbc:mysql://user-mysql:3306/users_db"
    depends_on:
      - discovery-server
      - config-server
    restart: always

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - "EUREKA_SERVER=http://discovery-server:8761/eureka"
      - "DB_URL=jdbc:mysql://auth-mysql:3306/auth_db"
    depends_on:
      - discovery-server
      - config-server
    restart: always

  carrinho-service:
    build: ./carrinho-service
    container_name: carrinho-service
    ports:
      - "8082:8082"
    environment:
      - "EUREKA_SERVER=http://discovery-server:8761/eureka"
      - "DB_URL=jdbc:mysql://carrinho-mysql:3306/carrinho_db"
    depends_on:
      - discovery-server
      - config-server
    restart: always

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    ports:
      - "8083:8083"
    environment:
      - "EUREKA_SERVER=http://discovery-server:8761/eureka"
      - "DB_URL=jdbc:mysql://catalog-mysql:3306/catalog_db"
    depends_on:
      - discovery-server
      - config-server
    restart: always


  auth-mysql:
    image: mysql:8.0
    container_name: auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: auth_db
    ports:
      - "6000:3306"
    volumes:
      - auth-mysql-data:/var/lib/mysql
      - ./auth-service/src/main/resources/db:/docker-entrypoint-initdb.d

  user-mysql:
    image: mysql:8.0
    container_name: user-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: users_db
    ports:
      - "6001:3306"
    volumes:
      - user-mysql-data:/var/lib/mysql
      - ./user-service/src/main/resources/db:/docker-entrypoint-initdb.d

  carrinho-mysql:
    image: mysql:8.0
    container_name: carrinho-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: carrinho_db
    ports:
      - "6002:3306"
    volumes:
      - carrinho-mysql-data:/var/lib/mysql
      - ./carrinho-service/src/main/resources/db:/docker-entrypoint-initdb.d

  catalog-mysql:
    image: mysql:8.0
    container_name: catalog-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: catalog_db
    ports:
      - "6003:3306"
    volumes:
      - catalog-mysql-data:/var/lib/mysql
      - ./catalog-service/src/main/resources/db:/docker-entrypoint-initdb.d

volumes:
  auth-mysql-data:
  user-mysql-data:
  carrinho-mysql-data:
  catalog-mysql-data: