name: Sistema de E-Commerce

on:
  push:
    branches:
      - main
      - test/ci
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:8080
          - 8081:8081
          - 8082:8082
          - 8083:8083
          - 8761:8761
          - 8888:8888
          - 6000:6000
          - 6001:6001
          - 6002:6002
          - 6003:6003

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Download latest JDK 17'
        run: |
          wget \
            --no-verbose \
            --directory-prefix $RUNNER_TEMP \
            https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/jdk-21_linux-x64_bin.tar.gz

      - name: Compile microservices
        run: |
          mvn -f ./discovery-server/pom.xml clean package -DskipTests
          mvn -f ./config-server/pom.xml clean package -DskipTests
          mvn -f ./auth-service/pom.xml clean package -DskipTests
          mvn -f ./user-service/pom.xml clean package -DskipTests
          mvn -f ./carrinho-service/pom.xml clean package -DskipTests
          mvn -f ./catalog-service/pom.xml clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation
        
      - name: Create cache directory
        run: mkdir -p /tmp/.buildx-cache

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build all services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run Docker Compose to start all services
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          sleep 30

      - name: Run Tests
        run: |
          docker-compose exec -T user-service mvn test
          docker-compose exec -T auth-service mvn test
          docker-compose exec -T catalog-service mvn test
          docker-compose exec -T carrinho-service mvn test

      - name: Shut down Docker Compose
        run: docker-compose down
